### ISSUE TITLE
BUG: Fix the google auth

### ISSUE THREAD

**Issue by Sayak-Bhunia** [Sayak-Bhunia/mystory#171] opened 2024-05-28 07:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The google authentication is not working,
this error keeps showing up.

![image](https://github.com/Sayak-Bhunia/mystory/assets/110457746/abf50ab6-12ec-475b-b78c-e2fb8ad233e3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by TenzDelek** [comment] 2024-05-28 15:55
@Sayak-Bhunia  I checked this issue, I believe this is happening due to empty secret in the .env file. 
<img width="485" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/6d945499-d633-48cc-946a-8e44dc4391a3">
which leads to no connection between the database or the auth that we are taking from google and github. 
do you know who was responsible for the auth part for this codebase?

**Comment by Sayak-Bhunia** [comment] 2024-05-28 16:00
> @Sayak-Bhunia  I checked this issue, I believe this is happening due to empty secret in the .env file. 
> <img width="485" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/6d945499-d633-48cc-946a-8e44dc4391a3">
> which leads to no connection between the database or the auth that we are taking from google and github. 
> do you know who was responsible for the auth part for this codebase? 

Aj should the secret be exposed?

**Comment by Sayak-Bhunia** [comment] 2024-05-28 16:00
> > @Sayak-Bhunia  I checked this issue, I believe this is happening due to empty secret in the .env file. 
> > <img width="485" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/6d945499-d633-48cc-946a-8e44dc4391a3">
> > which leads to no connection between the database or the auth that we are taking from google and github. 
> > do you know who was responsible for the auth part for this codebase? 
> 
> Ah, should the secret be exposed?

**Comment by TenzDelek** [comment] 2024-05-28 16:05
> > > @Sayak-Bhunia  I checked this issue, I believe this is happening due to empty secret in the .env file.
> > > <img alt="image" width="485" src="https://private-user-images.githubusercontent.com/122612557/334486153-6d945499-d633-48cc-946a-8e44dc4391a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MTI0ODMsIm5iZiI6MTcxNjkxMjE4MywicGF0aCI6Ii8xMjI2MTI1NTcvMzM0NDg2MTUzLTZkOTQ1NDk5LWQ2MzMtNDhjYy05NDZhLThlNDRkYzQzOTFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQxNjAzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTFlNzJjNWU4YzBiZDI0NTQyODBmMWYyNGE0NTJhN2U1OGUwMjY0MzdhNzhlZjBmN2ZkMGQ2ODc4NzU0MmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RPDaQeprPUUx9hmpAj4yq5pZVcPM6N5LArfCuVHx_Y0">
> > > which leads to no connection between the database or the auth that we are taking from google and github.
> > > do you know who was responsible for the auth part for this codebase?
> 
> Ah, should the secret be exposed?

i believe there is a  .env.example  file where we can put for developer to work on.(temporary secret) and after it is in final stage, we can changed that.
<img width="293" alt="image" src="https://github.com/Sayak-Bhunia/mystory/assets/122612557/52f9e551-3e98-4c33-9c6f-13a60dbba58d">

**Comment by Sayak-Bhunia** [comment] 2024-05-29 07:22
can you do that ?

**Comment by TenzDelek** [comment] 2024-05-29 08:21
Will try but don't assign me yet. Also can you check the pending pr

**Comment by Tomkndn** [comment] 2024-05-30 19:51
Hey, Is the issue solved?

**Comment by TenzDelek** [comment] 2024-05-31 05:16
@Tomkndn  about to finish.

**Comment by mohdjami** [comment] 2024-05-31 08:24
@Sayak-Bhunia , the issue is not related to Nextauth secret, it is related to the env variables google_id, google_secret is not set in vercel environment variables on vercel dashboard.

**Comment by Sayak-Bhunia** [comment] 2024-05-31 08:26
> @Sayak-Bhunia , the issue is not related to Nextauth secret, it is related to the env variables google_id, google_secret is not set in vercel environment variables on vercel dashboard.

Cam u tell me where can I get the secrets or what will be the secrets?

**Comment by TenzDelek** [comment] 2024-05-31 08:37
@Sayak-Bhunia it best to do this from your end and close this issue. The secret can be generated from your side. Only owner have the permission to have the access not the developer. 
You can go to the google console and generate the credentials. Same for GitHub.

**Comment by TenzDelek** [comment] 2024-05-31 08:39
If the next auth is set correctly, it should work after we generate the secret. If not we can raise issue depending on that

**Comment by mohdjami** [comment] 2024-05-31 08:42
@TenzDelek, GitHub and credentials login is working fine. Even after setting Google client Id and secret Google have restrictions from Google console it allow only some verified email to login right?

**Comment by TenzDelek** [comment] 2024-05-31 08:56
> @TenzDelek, GitHub and credentials login is working fine. Even after setting Google client Id and secret Google have restrictions from Google console it allow only some verified email to login right?

I believe if others providers are working fine, then the issue lies in the console setup, try checking the uri path are matching, the code base is deployed so give the url of that also. Maybe related to file structuring of the callback might also be related..

**Comment by Tomkndn** [comment] 2024-06-01 10:40
@Sayak-Bhunia  Add the below provided url and the production url to the Authorised redirect URIs in the google Oauth console of your generated Google Id and Google Secret window.
Also add the required Urls to the Authorised JavaScript origins too present in the top of this window.

Screenshot for the reference-
![image](https://github.com/Sayak-Bhunia/mystory/assets/105445488/2fc740af-1459-43c6-94d4-d426f6177d08)


It will solve the error.

**Closed** 2024-06-04 19:38 UTC
Labels: gssoc, level3
