### ISSUE TITLE
[Feature] Settings Page

### ISSUE THREAD

**Issue by mohdjami** [Sayak-Bhunia/mystory#109] opened 2024-05-17 06:12 UTC
I want to create a settings page for this application, where users can edit their username and other things. Assign this issue to me under GSSoC'24

**Comment by Sayak-Bhunia** [comment] 2024-05-17 08:21
assigned.

**Comment by shresthaPandit** [comment] 2024-05-17 08:47
Hey @Sayak-bhuniya, @Mohdjami, I believe I can work on this issue and raise a PR today or tomorrow. 
Approach: I will create a route in the backend to update the user name. And for frontend I will create a settings page where I will create a form to update the username.

Please assign me this issue under GSSoC'24 @sayak-bhuniya and @mohdjami. It will be my first contribution in GSSoC'24

**Comment by shresthaPandit** [comment] 2024-05-17 08:48
Hey @Sayak-Bhunia , @mohdjami , I believe I can work on this issue and raise a PR today or tomorrow. 
Approach: I will create a route in the backend to update the user name. And for frontend I will create a settings page where I will create a form to update the username.

Please assign me this issue under GSSoC'24 @sayak-bhuniya and @mohdjami. It will be my first contribution in GSSoC'24

**Comment by Sayak-Bhunia** [comment] 2024-05-17 08:50
> Hey @Sayak-Bhunia , @mohdjami , I believe I can work on this issue and raise a PR today or tomorrow. 
> Approach: I will create a route in the backend to update the user name. And for frontend I will create a settings page where I will create a form to update the username.
> 
> Please assign me this issue under GSSoC'24 @sayak-bhuniya and @mohdjami. It will be my first contribution in GSSoC'24

Its already assigned to @mohdjami.

**Comment by mohdjami** [comment] 2024-05-17 08:53
Okay @shresthaPandit, @Sayak-Bhunia assign him this issue. I am already working on 3 issues.

**Comment by Sayak-Bhunia** [comment] 2024-05-17 08:55
> Okay @shresthaPandit, @Sayak-Bhunia assign him this issue. I am already working on 3 issues.

Okay @mohdjami the issue is assigned to u @shresthaPandit.

**Comment by Sayak-Bhunia** [comment] 2024-05-17 08:56
> > Okay @shresthaPandit, @Sayak-Bhunia assign him this issue. I am already working on 3 issues.
> 
> Okay @mohdjami the issue is assigned to u @shresthaPandit.

@shresthaPandit best of luck 🤞 for ur valuable contribution🍀and do ⭐ the repo.

**Comment by shresthaPandit** [comment] 2024-05-17 09:50
Thanks @Sayak-Bhunia  I will start working today

**Comment by shresthaPandit** [comment] 2024-05-19 11:09
@Sayak-Bhunia  Do you need anything else in the settings page other than username update

**Comment by Sayak-Bhunia** [comment] 2024-05-19 12:11
> @Sayak-Bhunia  Do you need anything else in the settings page other than username update

No.

**Comment by shresthaPandit** [comment] 2024-05-21 18:21
hey @Sayak-Bhunia I have sucessfully created a PR please review and merge it .

**Closed** 2024-05-21 18:33 UTC
Labels: gssoc, level2
